#lang info
(define collection "opencage")
(define deps '("base" "net-lib" "racket-lib"))
(define pkg-desc "OpenCage Geocoding API client for Racket")
(define version "1.0.7")
(define license 'MIT)
(define license-file "LICENSE")
(define homepage "https://github.com/geonot/opencage-racket")
(define categories '(net))
(define tags '(geocode geocoding geolocation opencage))
(define scribblings '(("scribblings/opencage.scrbl" (multi-page) (library))))
(define authors '("OpenCage SDK Contributors"))
(define build-deps '("rackunit-lib" "scribble-lib" "racket-doc"))
(define test-deps '("rackunit-lib"))
