#lang info
(define collection "opencage")
(define deps '("base"))
(define pkg-desc "OpenCage Geocoding API client for Racket")
(define version "1.0.3")
(define license '("MIT"))
(define license-file "LICENSE")
(define homepage "https://github.com/geonot/opencage-racket")
(define categories '(net))
(define tags '(geocode geocoding geolocation opencage))
(define scribblings '(("scribblings/opencage.scrbl")))
(define authors '("OpenCage SDK Contributors"))
(define build-deps '("rackunit-lib"))
