name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        racket-version: [ "8.12", "8.14", "8.16", "current" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1
        with:
          version: ${{ matrix.racket-version }}
      - name: Install Package (link)
        run: raco pkg install --auto --name opencage .
      - name: Build & Docs
        run: raco setup -l opencage
      - name: Run Tests
        env:
          # Optionally set OPENCAGE_API_KEY in repo secrets to exercise network tests fully
          OPENCAGE_API_KEY: ${{ secrets.OPENCAGE_API_KEY }}
        run: raco test -x -p opencage || raco test tests
      - name: Scribble Docs (HTML)
        run: raco scribble --htmls --dest scribble-out scribblings/opencage.scrbl
      - name: Archive Docs
        uses: actions/upload-artifact@v4
        with:
          name: docs-${{ matrix.racket-version }}
          path: scribble-out
