name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        racket-version: [ "8.14", "8.16", "8.18", "current" ]
    steps:
      - uses: actions/checkout@v4
      - name: Cache Racket pkg dir
        uses: actions/cache@v4
        with:
          path: ~/.racket
          key: racket-${{ matrix.racket-version }}-${{ hashFiles('info.rkt') }}
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.14
        with:
          version: ${{ matrix.racket-version }}
          architecture: x64
          distribution: full
          variant: CS
      - name: Install Package
        run: raco pkg install --auto --name opencage "$GITHUB_WORKSPACE"
      - name: Build
        run: raco setup -l opencage
      - name: Run Tests (offline-safe)
        env:
          OPENCAGE_API_KEY: ${{ secrets.OPENCAGE_API_KEY }}
          PLT_PKG_BUILD_SERVICE: 1
          CI: true
        run: raco test -x -p opencage

  docs:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Racket (current)
        uses: Bogdanp/setup-racket@v1.14
        with:
          version: current
          architecture: x64
          distribution: full
          variant: CS
      - name: Install Package
        run: raco pkg install --auto --name opencage "$GITHUB_WORKSPACE"
      - name: Build Docs
        run: raco setup -l opencage
      - name: Generate HTML (standalone)
        run: raco scribble --htmls --dest scribble-out scribblings/opencage.scrbl
      - name: Archive Docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: scribble-out
